name = "jobber-proxy"
main = "jobber-proxy.js"
compatibility_date = "2025-08-26"

[[routes]]
pattern = "https://elagagefrancois.com/api/*"
zone_id = "__ZONE_ID__"

[vars]
# (empty; using env vairables and secrets instead)

[env.dev]
account_id = "__ACCOUNT_ID__"
route = "https://elagagefrancois.com/api/*"

[env.production]
account_id = "__ACCOUNT_ID__"
route = "https://elagagefrancois.com/api/*"