name = "jobber-proxy"
main = "jobber-proxy.js"
compatibility_date = "2025-07-23"

[[routes]]
pattern = "https://service-delagage-francois.pages.dev/api/*"
zone_id = "your-zone-id"

[vars]
# (empty; using env vairables and secrets instead)

[env.dev]
account_id = "your-account-id"
route = "https://dev-api.service-delagage-francois.pages.dev/api/*"

[env.production]
account_id = "your-account-id"
route = "https://service-delagage-francois.pages.dev/api/*"