name = "jobber-proxy"
main = "jobber-proxy.js"
compatibility_date = "2025-08-26"

[[routes]]
pattern = "https://elagagefrancois.com/api/*"
zone_id = "706de84a4c8efaa6d68e72d35bef79b3"

[vars]
# (empty; using env vairables and secrets instead)

[env.dev]
account_id = "706de84a4c8efaa6d68e72d35bef79b3"
route = "https://elagagefrancois.com/api/*"

[env.production]
account_id = "706de84a4c8efaa6d68e72d35bef79b3"
route = "https://elagagefrancois.com/api/*"